### ISSUE TITLE
Unable to find environment variable for $GITHUB_STEP_SUMMARY. Check if your runtime environment supports job summaries.

### ISSUE THREAD

**Issue by jclaveau** [eratio08/vitest-github-actions-reporter#45]
I had to configure it the following way to keep my tests working locally
```
    reporters: [
      'default',
      process.env.GITHUB_STEP_SUMMARY ? new GithubActionsReporter() : null,
    ],
```

**Comment by eratio08** [comment]
The variable is available on github runner https://docs.github.com/en/actions/learn-github-actions/variables. You should not try to use this reporter locally. So you workaround will essentially do that
